# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 21:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('checked', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(default=datetime.datetime.now)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.OurService')),
                ('recipient_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='request.Country')),
                ('sender_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='request.Country')),
            ],
        ),
    ]
