# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='details',
        ),
    ]
