# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_remove_request_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
