# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20171123_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.OurService'),
        ),
        migrations.DeleteModel(
            name='Method',
        ),
    ]
