# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-23 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_auto_20171210_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='recipient_country',
        ),
        migrations.RemoveField(
            model_name='request',
            name='sender_country',
        ),
        migrations.AddField(
            model_name='request',
            name='dimentions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='goods_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='recipient',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='sender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='request',
            name='method',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
