# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('ourservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.OurService')),
            ],
        ),
        migrations.RenameModel(
            old_name='OpeningHours',
            new_name='OpeningHour',
        ),
        migrations.RenameModel(
            old_name='SocialNetworks',
            new_name='SocialNetwork',
        ),
    ]
