# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='countries_covered',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='name',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='hardworking_people',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='offices_worldwide',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='years_of_experiences',
        ),
        migrations.AddField(
            model_name='statistic',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
