# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20171205_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='phone',
        ),
    ]
