# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 02:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20171206_0210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
