# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_delete_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetail',
            name='ourservice',
        ),
        migrations.DeleteModel(
            name='OurService',
        ),
        migrations.DeleteModel(
            name='ServiceDetail',
        ),
    ]
