# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_servicedetail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200, null=True),
        ),
    ]
