# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20171206_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourservice',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
