# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 10:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('checked', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
